networks:
  wordpress:
    name: wordpress

services:
  nginx:
    image: nginx:latest
    container_name: nginx_container
    depends_on:
      - wordpress
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - wordpress_data:/var/www/html
    ports:
      - "8080:80"
    networks:
      - wordpress

  mysql:
    image: mysql:latest
    container_name: wordpress_mysql
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wp_database
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: rootpassword
    networks:
      - wordpress

  wordpress:
    image: wordpress:php8.2-fpm
    container_name: wordpress_container
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: wp_database
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: admin
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - wordpress

volumes:
  db_data:
  wordpress_data:
